# -*- coding: utf-8 -*-
"""Bag-of-Words (BoW) Vectorization and Representation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P27dDfyjx0uyFOEPcyv3Sb2_4NGgkUV9
"""

from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

# Step 1: Define a small custom corpus
corpus = [
    "Natural language processing is fun",
    "I love learning natural language processing",
    "Language models are powerful tools",
    "Processing text data requires careful cleaning"
]

# Step 2: Create the CountVectorizer object
# (lowercase=True by default, stop_words can be set to 'english' if needed)
vectorizer = CountVectorizer()

# Step 3: Fit the vectorizer on the corpus and transform it into vectors
bow_matrix = vectorizer.fit_transform(corpus)

# Step 4: Extract the vocabulary (feature names)
vocabulary = vectorizer.get_feature_names_out()

# Step 5: Convert the sparse matrix to a dense array for display
bow_array = bow_matrix.toarray()

# Step 6: Display the results in a readable DataFrame
bow_df = pd.DataFrame(bow_array, columns=vocabulary,
                       index=[f"Doc{i+1}" for i in range(len(corpus))])

print("Corpus:")
for i, doc in enumerate(corpus, start=1):
    print(f"  Doc{i}: {doc}")

print("\nVocabulary (unique words found):")
print(vocabulary)

print("\nBag-of-Words Matrix (word counts per document):")
print(bow_df)

print("\nShape of BoW matrix (documents x vocabulary size):", bow_matrix.shape)