# -*- coding: utf-8 -*-
"""Copy of Stemming and Lemmatization on Sample Text

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FAahx6HxXkFKNKx-_B5Xa-qNYlvmP2YZ
"""

import nltk
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer, WordNetLemmatizer

# Download required NLTK resources (only needs to run once)
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('wordnet')
nltk.download('omw-1.4')

sample_text = (
    "The children were running and playing happily in the gardens "
    "while the leaves were falling from the trees."
)

print("Original Text:\n", sample_text)

# Tokenize the text into words
words = word_tokenize(sample_text)

# ---------------------------------------------------------
# Stemming using Porter Stemmer
# ---------------------------------------------------------
stemmer = PorterStemmer()
stemmed_words = [stemmer.stem(word) for word in words]

# ---------------------------------------------------------
# Lemmatization using WordNet Lemmatizer
# ---------------------------------------------------------
lemmatizer = WordNetLemmatizer()
lemmatized_words = [lemmatizer.lemmatize(word, pos='v') for word in words]

# ---------------------------------------------------------
# Display comparison in a table format
# ---------------------------------------------------------
print(f"\n{'Original Word':<15}{'Stemmed Word':<15}{'Lemmatized Word':<15}")
print("-" * 45)
for orig, stem, lemma in zip(words, stemmed_words, lemmatized_words):
    print(f"{orig:<15}{stem:<15}{lemma:<15}")