# -*- coding: utf-8 -*-
"""Copy of Tokenization of Sentences and Words using NLTK and spaCy

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uhcr55r5xDZ24ucaxVYrqdrYAjAazelR
"""

# ---------------------------------------------------------
# Part A: Tokenization using NLTK
# ---------------------------------------------------------
import nltk
from nltk.tokenize import sent_tokenize, word_tokenize

# Download required NLTK data (only needs to run once)
nltk.download('punkt')
nltk.download('punkt_tab')

sample_text = (
    "Natural Language Processing is a fascinating field of AI. "
    "It helps computers understand human language. "
    "Isn't that amazing?"
)

print("=" * 60)
print("PART A: TOKENIZATION USING NLTK")
print("=" * 60)

print("\nOriginal Text:\n", sample_text)

# Sentence Tokenization
sentences = sent_tokenize(sample_text)
print("\n--- Sentence Tokens (NLTK) ---")
for i, sent in enumerate(sentences, 1):
    print(f"{i}. {sent}")

# Word Tokenization
words = word_tokenize(sample_text)
print("\n--- Word Tokens (NLTK) ---")
print(words)
print(f"\nTotal number of words: {len(words)}")


# Part B: Tokenization using spaCy
# ---------------------------------------------------------
import spacy

# Load the small English model
# (Install once using: python -m spacy download en_core_web_sm)
nlp = spacy.load("en_core_web_sm")

doc = nlp(sample_text)

print("\n" + "=" * 60)
print("PART B: TOKENIZATION USING spaCy")
print("=" * 60)

# Sentence Tokenization
print("\n--- Sentence Tokens (spaCy) ---")
for i, sent in enumerate(doc.sents, 1):
    print(f"{i}. {sent.text}")

# Word Tokenization
spacy_words = [token.text for token in doc]
print("\n--- Word Tokens (spaCy) ---")
print(spacy_words)
print(f"\nTotal number of tokens: {len(spacy_words)}")