# -*- coding: utf-8 -*-
"""Named Entity Recognition (NER) using spaCy

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16KjYJ-UE87kIp2baAmC2ev-cA7lcfA3X
"""

import spacy
from spacy import displacy

# Load the small English model
# (Install once using: python -m spacy download en_core_web_sm)
nlp = spacy.load("en_core_web_sm")

text = (
    "Apple Inc. was founded by Steve Jobs and Steve Wozniak in "
    "Cupertino, California on April 1, 1976. The company is now "
    "worth over $2 trillion and is led by Tim Cook."
)

print("Original Text:\n", text)

doc = nlp(text)

print("\n--- Named Entities Found ---")
for ent in doc.ents:
    print(f"{ent.text} -> {ent.label_}")

print(f"\nTotal entities found: {len(doc.ents)}")

# Optional: save a visualization of the entities as an HTML file
# Removed page=True and added jupyter=False to ensure displacy.render returns a string
html_string = displacy.render(doc, style="ent", jupyter=False)

with open("ner_visualization.html", "w", encoding="utf-8") as f:
    f.write(html_string)
print("\nEntity visualization saved to 'ner_visualization.html'")