# -*- coding: utf-8 -*-
"""Parsing and Chunking using RegEx and spaCy

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fw-vR3vQ6PllfqX5fzREc96SXC-y79Y3
"""

# ---------------------------------------------------------
# Part A: Chunking using NLTK RegexpParser (Regular Expressions)
# ---------------------------------------------------------
import nltk
from nltk import word_tokenize, pos_tag, RegexpParser

# Download required NLTK resources (only needs to run once)
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('averaged_perceptron_tagger')
nltk.download('averaged_perceptron_tagger_eng')

sentence = "The little brown dog barked at the tall mailman near the old gate."

print("=" * 60)
print("PART A: CHUNKING USING REGEX (NLTK RegexpParser)")
print("=" * 60)
print("\nSentence:", sentence)

tokens = word_tokenize(sentence)
pos_tags = pos_tag(tokens)
print("\nPOS Tags:", pos_tags)

# Grammar rule: a Noun Phrase (NP) chunk =
#   optional determiner (DT) + any number of adjectives (JJ) + a noun (NN)
grammar = "NP: {<DT>?<JJ>*<NN>}"
chunk_parser = RegexpParser(grammar)
chunk_tree = chunk_parser.parse(pos_tags)

print("\n--- Chunked Output (Tree) ---")
print(chunk_tree)

print("\n--- Extracted Noun Phrase Chunks ---")
for subtree in chunk_tree.subtrees():
    if subtree.label() == 'NP':
        phrase = " ".join(word for word, tag in subtree.leaves())
        print("-", phrase)


# ---------------------------------------------------------
# Part B: Noun-phrase Chunking using spaCy
# ---------------------------------------------------------
import spacy

nlp = spacy.load("en_core_web_sm")
doc = nlp(sentence)

print("\n" + "=" * 60)
print("PART B: NOUN-PHRASE CHUNKING USING spaCy")
print("=" * 60)

print("\n--- Noun Chunks (spaCy) ---")
for chunk in doc.noun_chunks:
    print("-", chunk.text)