# -*- coding: utf-8 -*-
"""POS Tagging using NLTK

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CPBgV27GhHDZbQCXPVqJ5z0cXLjcYTIJ
"""

# ---------------------------------------------------------
# Part A: POS Tagging using NLTK
# ---------------------------------------------------------
import nltk
from nltk.tokenize import word_tokenize

# Download required NLTK resources (only needs to run once)
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('averaged_perceptron_tagger')
nltk.download('averaged_perceptron_tagger_eng')

sentence = "The quick brown fox jumps over the lazy dog near the river."

print("=" * 60)
print("PART A: POS TAGGING USING NLTK")
print("=" * 60)
print("\nSentence:", sentence)

tokens = word_tokenize(sentence)
nltk_pos_tags = nltk.pos_tag(tokens)

print("\n--- POS Tags (NLTK) ---")
for word, tag in nltk_pos_tags:
    print(f"{word:<10} -> {tag}")


# ---------------------------------------------------------
# Part B: POS Tagging using spaCy
# ---------------------------------------------------------
import spacy

nlp = spacy.load("en_core_web_sm")
doc = nlp(sentence)

print("\n" + "=" * 60)
print("PART B: POS TAGGING USING spaCy")
print("=" * 60)

for token in doc:
    print(f"{token.text:<10} -> {token.pos_} ({token.tag_})")