# -*- coding: utf-8 -*-
"""Stop-word Removal from a Document

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UPImKxaanu97e9LE3mPEXyPAc7f8Bx2m
"""

import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

# Download required NLTK resources (only needs to run once)
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')

document = (
    "This is a sample document that we are using to demonstrate "
    "the process of removing stop words from a given piece of text "
    "using the Natural Language Toolkit in Python."
)

print("Original Document:\n", document)

# Load English stop words
stop_words = set(stopwords.words('english'))

# Tokenize the document
words = word_tokenize(document)

# Filter out stop words (case-insensitive), keep only alphabetic tokens
filtered_words = [
    word for word in words
    if word.lower() not in stop_words and word.isalpha()
]

removed_words = [
    word for word in words
    if word.lower() in stop_words
]

print("\n--- Tokens Removed (Stop Words) ---")
print(removed_words)

print("\n--- Text After Stop-word Removal ---")
print(" ".join(filtered_words))

print(f"\nOriginal word count : {len(words)}")
print(f"Filtered word count  : {len(filtered_words)}")