# -*- coding: utf-8 -*-
"""Cosine Similarity Computation between Text Documents

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-xEbji8C3lBgETFxgF87-M3_TT8Qu1o7
"""

import re
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

pd.set_option("display.width", 200)

# ---------------------------------------------------------------
# 1. Documents
# ---------------------------------------------------------------
documents = [
    "Natural language processing helps computers understand text",
    "Machine learning is used to build natural language processing systems",
    "The weather today is sunny with a chance of rain",
    "Deep learning is a subset of machine learning",
]
index = [f"Doc {i}" for i in range(1, len(documents) + 1)]

print("=" * 60)
print("DOCUMENTS")
print("=" * 60)
for name, doc in zip(index, documents):
    print(f"{name}: {doc}")


# ---------------------------------------------------------------
# 2. Cosine similarity from scratch (on TF-IDF vectors)
#    cos(A, B) = (A . B) / (||A|| * ||B||)
# ---------------------------------------------------------------
def cosine_sim_manual(vec_a, vec_b):
    dot = np.dot(vec_a, vec_b)
    norm_a = np.linalg.norm(vec_a)
    norm_b = np.linalg.norm(vec_b)
    if norm_a == 0 or norm_b == 0:
        return 0.0
    return dot / (norm_a * norm_b)


vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform(documents).toarray()

print("\n" + "=" * 60)
print("TF-IDF VECTORS")
print("=" * 60)
print(pd.DataFrame(tfidf_matrix, columns=vectorizer.get_feature_names_out(), index=index).round(3))

n = len(documents)
manual_sim = np.zeros((n, n))
for i in range(n):
    for j in range(n):
        manual_sim[i, j] = cosine_sim_manual(tfidf_matrix[i], tfidf_matrix[j])

manual_sim_df = pd.DataFrame(manual_sim.round(3), index=index, columns=index)

print("\n" + "=" * 60)
print("COSINE SIMILARITY MATRIX (FROM SCRATCH)")
print("=" * 60)
print(manual_sim_df)

# ---------------------------------------------------------------
# 3. Cosine similarity using scikit-learn
# ---------------------------------------------------------------
sk_sim = cosine_similarity(tfidf_matrix)
sk_sim_df = pd.DataFrame(sk_sim.round(3), index=index, columns=index)

print("\n" + "=" * 60)
print("COSINE SIMILARITY MATRIX (sklearn)")
print("=" * 60)
print(sk_sim_df)

print("\nManual matrix matches sklearn matrix:", np.allclose(manual_sim, sk_sim))

# ---------------------------------------------------------------
# 4. Most similar document pair (excluding a document with itself)
# ---------------------------------------------------------------
sim_copy = sk_sim.copy()
np.fill_diagonal(sim_copy, -1)
i, j = np.unravel_index(np.argmax(sim_copy), sim_copy.shape)

print("\n" + "=" * 60)
print("MOST SIMILAR DOCUMENT PAIR")
print("=" * 60)
print(f"{index[i]} & {index[j]}  (similarity = {sim_copy[i, j]:.3f})")
print(f"  {index[i]}: {documents[i]}")
print(f"  {index[j]}: {documents[j]}")

# ---------------------------------------------------------------
# 5. Rank documents by similarity to a query
# ---------------------------------------------------------------
query = "How does machine learning work with text data?"
query_vec = vectorizer.transform([query]).toarray()

query_sim = cosine_similarity(query_vec, tfidf_matrix)[0]
ranking = sorted(zip(index, documents, query_sim), key=lambda x: x[2], reverse=True)

print("\n" + "=" * 60)
print(f"DOCUMENTS RANKED BY SIMILARITY TO QUERY:\n'{query}'")
print("=" * 60)
for name, doc, score in ranking:
    print(f"{score:.3f}  {name}: {doc}")