# -*- coding: utf-8 -*-
"""GloVe Embeddings Loading and Vector Representation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_XrDvuTgSQKD81oRO-IsYOU73d3MDWgX
"""

import numpy as np
import gensim.downloader as api

# 1. Load pretrained GloVe embeddings
print("Loading GloVe model...")

glove_model = api.load("glove-wiki-gigaword-50")

print("GloVe model loaded successfully!")

# 2. Display the vector representation of a word
word = "computer"

if word in glove_model:
    vector = glove_model[word]

    print("\nWord:", word)
    print("Word Vector:")
    print(vector)

    print("\nVector Dimension:", len(vector))
else:
    print("Word not found in vocabulary")

# 3. Find similar words
print("\nWords similar to 'computer':")

similar_words = glove_model.most_similar("computer", topn=5)

for word, score in similar_words:
    print(word, ":", round(score, 4))

# 4. Calculate similarity between two words
word1 = "king"
word2 = "queen"

similarity = glove_model.similarity(word1, word2)

print("\nSimilarity between", word1, "and", word2)
print(round(similarity, 4))

# 5. Check another word vector
word = "king"

print("\nVector representation of 'king':")
print(glove_model[word])

print("\nProgram executed successfully!")