# -*- coding: utf-8 -*-
"""Information Extraction (IE) from Structured/Unstructured Documents

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nmiJ9-JWUiYWW2hLqy-RdxpFMwUD3xku
"""

# Information Extraction from Structured and Unstructured Documents

import spacy
import pandas as pd
import re

# Step 1: Load the spaCy English NLP model
nlp = spacy.load("en_core_web_sm")

# Step 2: Create an unstructured document
text = """
Aniket Kumar works at Google in Bengaluru.
He attended a meeting on 15 September 2026.
For contact, email aniket@example.com or call 9876543210.
Google is a technology company.
"""

# Step 3: Extract named entities from unstructured text
doc = nlp(text)

print("INFORMATION EXTRACTION FROM UNSTRUCTURED TEXT")
print("-" * 50)

print("\nNamed Entities:")

for ent in doc.ents:
    print(ent.text, ":", ent.label_)

# Step 4: Extract email addresses using Regular Expressions
emails = re.findall(
    r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b',
    text
)

# Step 5: Extract phone numbers
phones = re.findall(
    r'\b(?:\+91[-\s]?)?[6-9]\d{9}\b',
    text
)

print("\nEmail Addresses:")
for email in emails:
    print(email)

print("\nPhone Numbers:")
for phone in phones:
    print(phone)

# Step 6: Extract information from structured data
data = {
    "Name": ["Aniket Kumar", "Rahul Sharma"],
    "Organization": ["Google", "Microsoft"],
    "City": ["Bengaluru", "Hyderabad"],
    "Email": ["aniket@example.com", "rahul@example.com"]
}

df = pd.DataFrame(data)

print("\nINFORMATION EXTRACTION FROM STRUCTURED DATA")
print("-" * 50)

print(df.to_string(index=False))

# Step 7: Save extracted structured data
df.to_csv("extracted_information.csv", index=False)

print("\nExtracted data saved to extracted_information.csv")