# -*- coding: utf-8 -*-
"""Information Retrieval System with Ranking using TF-IDF

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_1nkXr25tV5gUs-km1D7gzF4EtO3SClj
"""

# Information Retrieval System with Ranking using TF-IDF

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Step 1: Create a document collection
documents = [
    "Machine learning is a branch of artificial intelligence",
    "Deep learning uses neural networks for machine learning",
    "Python is a popular programming language",
    "Information retrieval helps users search relevant documents",
    "TF-IDF is used to rank documents based on query relevance",
    "Artificial intelligence is transforming modern technology"
]

# Step 2: Assign document IDs
document_ids = [f"Document {i+1}" for i in range(len(documents))]

# Step 3: Convert documents into TF-IDF vectors
vectorizer = TfidfVectorizer(stop_words="english")

tfidf_matrix = vectorizer.fit_transform(documents)

print("Information Retrieval System")
print("-" * 50)

# Step 4: Take a search query
query = input("\nEnter your search query: ")

# Step 5: Convert query into TF-IDF vector
query_vector = vectorizer.transform([query])

# Step 6: Calculate cosine similarity
similarity_scores = cosine_similarity(
    query_vector,
    tfidf_matrix
).flatten()

# Step 7: Rank documents by similarity score
ranked_indices = similarity_scores.argsort()[::-1]

# Step 8: Display ranked results
print("\nSearch Results (Ranked):")
print("-" * 50)

found = False

for rank, index in enumerate(ranked_indices, start=1):

    score = similarity_scores[index]

    # Display only relevant documents
    if score > 0:
        found = True

        print(f"\nRank: {rank}")
        print("Document ID:", document_ids[index])
        print("Similarity Score:", round(score, 4))
        print("Content:", documents[index])

if not found:
    print("No relevant documents found.")

print("\nSearch completed.")