# -*- coding: utf-8 -*-
"""N-Gram Model (Uni-, Bi-, Tri-gram) Generation from Corpus

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MtvKYpLrYP_4pWObTOmmWw5-3qsEMBdd
"""

import re
from collections import Counter

import pandas as pd

try:
    from nltk.util import ngrams as nltk_ngrams
    NLTK_AVAILABLE = True
except ImportError:
    NLTK_AVAILABLE = False

# ---------------------------------------------------------------
# 1. Corpus
# ---------------------------------------------------------------
corpus = (
    "Natural language processing enables computers to understand human language. "
    "Language processing tasks include tokenization, parsing, and translation. "
    "Natural language understanding is a key part of artificial intelligence."
)

print("=" * 60)
print("CORPUS")
print("=" * 60)
print(corpus)


def tokenize(text):
    return re.findall(r"[a-zA-Z]+", text.lower())


tokens = tokenize(corpus)
print("\nTokens:", tokens)
print("Total tokens:", len(tokens))


# ---------------------------------------------------------------
# 2. Manual n-gram generator
# ---------------------------------------------------------------
def generate_ngrams(token_list, n):
    return [tuple(token_list[i : i + n]) for i in range(len(token_list) - n + 1)]


unigrams = generate_ngrams(tokens, 1)
bigrams = generate_ngrams(tokens, 2)
trigrams = generate_ngrams(tokens, 3)

print("\n" + "=" * 60)
print("MANUAL N-GRAM GENERATION")
print("=" * 60)
print(f"Unigrams ({len(unigrams)}):", unigrams[:10], "...")
print(f"Bigrams  ({len(bigrams)}):", bigrams[:10], "...")
print(f"Trigrams ({len(trigrams)}):", trigrams[:10], "...")

# ---------------------------------------------------------------
# 3. Cross-check with NLTK, if available
# ---------------------------------------------------------------
if NLTK_AVAILABLE:
    nltk_bigrams = list(nltk_ngrams(tokens, 2))
    print(
        "\nManual bigrams match nltk.util.ngrams:",
        bigrams == nltk_bigrams,
    )
else:
    print("\n(nltk not installed — skipping cross-check; manual implementation used throughout.)")

# ---------------------------------------------------------------
# 4. Frequency distribution for each n-gram order
# ---------------------------------------------------------------
def show_frequencies(ngram_list, title, top_n=10):
    counts = Counter(ngram_list)
    df = pd.DataFrame(
        [(" ".join(gram), freq) for gram, freq in counts.most_common(top_n)],
        columns=["n-gram", "frequency"],
    )
    print(f"\n{title} (top {min(top_n, len(counts))} of {len(counts)} unique):")
    print(df.to_string(index=False))
    return counts


print("\n" + "=" * 60)
print("FREQUENCY DISTRIBUTIONS")
print("=" * 60)
uni_counts = show_frequencies(unigrams, "UNIGRAM FREQUENCIES")
bi_counts = show_frequencies(bigrams, "BIGRAM FREQUENCIES")
tri_counts = show_frequencies(trigrams, "TRIGRAM FREQUENCIES")

# ---------------------------------------------------------------
# 5. Simple next-word prediction using bigram counts
# ---------------------------------------------------------------
def predict_next_word(word, bigram_counts):
    candidates = {b[1]: c for b, c in bigram_counts.items() if b[0] == word}
    if not candidates:
        return None
    return max(candidates, key=candidates.get)


print("\n" + "=" * 60)
print("NEXT-WORD PREDICTION FROM BIGRAM MODEL")
print("=" * 60)
for w in ["natural", "language", "processing"]:
    print(f"After '{w}' -> '{predict_next_word(w, bi_counts)}'")

# ---------------------------------------------------------------
# 6. Generic function: build n-grams for any n
# ---------------------------------------------------------------
def build_ngram_model(text, n):
    toks = tokenize(text)
    return Counter(generate_ngrams(toks, n))


print("\n" + "=" * 60)
print("4-GRAMS (GENERIC FUNCTION, n=4)")
print("=" * 60)
four_grams = build_ngram_model(corpus, 4)
for gram, freq in four_grams.most_common(5):
    print(" ".join(gram), "->", freq)