# -*- coding: utf-8 -*-
"""Sentiment Analysis using TextBlob and VADER

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vIUqqe6aFhkw13Uy7TCNbGZ5M6P5xdX_
"""

# Install TextBlob and VADER sentiment analyzer if not already installed
!pip install textblob vaderSentiment

# Sentiment Analysis using TextBlob and VADER

from textblob import TextBlob
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

# Step 1: Create sample text data
texts = [
    "I love this movie. It is amazing!",
    "This product is very bad and disappointing.",
    "The movie is okay, nothing special.",
    "The food was absolutely fantastic!",
    "I am not happy with this service."
]

# Step 2: Initialize VADER analyzer
analyzer = SentimentIntensityAnalyzer()

# Step 3: Perform sentiment analysis
for text in texts:

    print("\nText:", text)

    # TextBlob sentiment analysis
    blob = TextBlob(text)
    polarity = blob.sentiment.polarity
    subjectivity = blob.sentiment.subjectivity

    if polarity > 0:
        textblob_sentiment = "Positive"
    elif polarity < 0:
        textblob_sentiment = "Negative"
    else:
        textblob_sentiment = "Neutral"

    print("\nTextBlob:")
    print("Polarity:", round(polarity, 3))
    print("Subjectivity:", round(subjectivity, 3))
    print("Sentiment:", textblob_sentiment)

    # VADER sentiment analysis
    scores = analyzer.polarity_scores(text)
    compound = scores["compound"]

    if compound >= 0.05:
        vader_sentiment = "Positive"
    elif compound <= -0.05:
        vader_sentiment = "Negative"
    else:
        vader_sentiment = "Neutral"

    print("\nVADER:")
    print("Positive Score:", round(scores["pos"], 3))
    print("Negative Score:", round(scores["neg"], 3))
    print("Neutral Score:", round(scores["neu"], 3))
    print("Compound Score:", round(compound, 3))
    print("Sentiment:", vader_sentiment)

    print("-" * 50)