# -*- coding: utf-8 -*-
"""Text Classification using Naïve Bayes/SVM with TF-IDF

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13r5qksn3uO1iiQNQoU37WFMk3UpTKfvz
"""

# Text Classification using Naive Bayes and SVM with TF-IDF

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score, classification_report

# Step 1: Create a sample dataset
texts = [
    "I love this movie, it is amazing",
    "This film is wonderful and fantastic",
    "What a great and excellent movie",
    "I really enjoyed this amazing film",
    "The movie was very good",
    "This is a fantastic and enjoyable movie",
    "I hate this movie, it is terrible",
    "This film is boring and disappointing",
    "What a bad and horrible movie",
    "I did not like this terrible film",
    "The movie was very boring",
    "This is a poor and awful movie"
]

# Labels: 1 = Positive, 0 = Negative
labels = [
    1, 1, 1, 1, 1, 1,
    0, 0, 0, 0, 0, 0
]

# Step 2: Convert text into TF-IDF features
vectorizer = TfidfVectorizer()

X = vectorizer.fit_transform(texts)
y = labels

# Step 3: Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.25,
    random_state=42,
    stratify=y
)

# Step 4: Train Naive Bayes classifier
nb_model = MultinomialNB()
nb_model.fit(X_train, y_train)

# Step 5: Train SVM classifier
svm_model = LinearSVC(random_state=42)
svm_model.fit(X_train, y_train)

# Step 6: Make predictions
nb_predictions = nb_model.predict(X_test)
svm_predictions = svm_model.predict(X_test)

# Step 7: Display accuracy
print("Naive Bayes Accuracy:",
      accuracy_score(y_test, nb_predictions))

print("SVM Accuracy:",
      accuracy_score(y_test, svm_predictions))

# Step 8: Test new sentences
new_texts = [
    "This movie is amazing and wonderful",
    "This film is boring and terrible"
]

new_features = vectorizer.transform(new_texts)

nb_result = nb_model.predict(new_features)
svm_result = svm_model.predict(new_features)

# Step 9: Display classification results
for i, text in enumerate(new_texts):
    print("\nText:", text)

    if nb_result[i] == 1:
        print("Naive Bayes: Positive")
    else:
        print("Naive Bayes: Negative")

    if svm_result[i] == 1:
        print("SVM: Positive")
    else:
        print("SVM: Negative")

# Step 10: Display classification report
print("\nNaive Bayes Classification Report:")
print(classification_report(
    y_test,
    nb_predictions,
    zero_division=0
))

print("SVM Classification Report:")
print(classification_report(
    y_test,
    svm_predictions,
    zero_division=0
))