# -*- coding: utf-8 -*-
"""Text Similarity using Word Mover's Distance (WMD)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/161oAawvR0yy5c3xcEYX543_mq8I-ELR9
"""

# Install gensim if not already installed
!pip install gensim
# Install the Python Optimal Transport (POT) library for Word Mover's Distance
!pip install POT

import gensim.downloader as api
from gensim.parsing.preprocessing import STOPWORDS

# 1. Load pretrained word embeddings
print("Loading word embeddings...")

model = api.load("glove-wiki-gigaword-50")

print("Model loaded successfully!")

# 2. Create two text documents
text1 = "I love machine learning and artificial intelligence"
text2 = "I enjoy studying AI and deep learning"

print("\nText 1:", text1)
print("Text 2:", text2)

# 3. Preprocess the documents
def preprocess(text):
    words = text.lower().split()

    # Remove stopwords and words not in the model vocabulary
    words = [
        word for word in words
        if word not in STOPWORDS and word in model.key_to_index
    ]

    return words

words1 = preprocess(text1)
words2 = preprocess(text2)

print("\nPreprocessed Text 1:", words1)
print("Preprocessed Text 2:", words2)

# 4. Calculate Word Mover's Distance
distance = model.wmdistance(words1, words2)

print("\nWord Mover's Distance:")
print(distance)

# 5. Interpret the result
if distance == float("inf"):
    print("WMD could not be calculated.")
else:
    print("\nSimilarity Interpretation:")

    if distance < 1:
        print("The documents are semantically very close.")
    elif distance < 2:
        print("The documents have some semantic similarity.")
    else:
        print("The documents are relatively far apart.")

# 6. Compare a document with itself
same_distance = model.wmdistance(words1, words1)

print("\nDistance between identical documents:")
print(same_distance)