# -*- coding: utf-8 -*-
"""TF-IDF Implementation and Comparison with BoW

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y2EAsgFDV1gNRxT8iSler16u6vDiiVal
"""

import math
import re
from collections import Counter

import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

pd.set_option("display.width", 200)
pd.set_option("display.max_columns", None)

# ---------------------------------------------------------------
# 1. Sample corpus
# ---------------------------------------------------------------
corpus = [
    "the cat sat on the mat",
    "the dog sat on the log",
    "cats and dogs are pets",
    "the cat chased the dog",
]
index = [f"Doc {i}" for i in range(1, len(corpus) + 1)]

print("=" * 60)
print("CORPUS")
print("=" * 60)
for name, doc in zip(index, corpus):
    print(f"{name}: {doc}")


# ---------------------------------------------------------------
# 2. TF-IDF from scratch
#    TF(t, d)  = count(t in d) / total terms in d
#    IDF(t)    = log((1 + N) / (1 + df(t))) + 1     (sklearn's smoothed IDF)
#    TF-IDF    = TF * IDF   (then L2-normalised per document)
# ---------------------------------------------------------------
def tokenize(text):
    return re.findall(r"[a-z]+", text.lower())


tokenized = [tokenize(d) for d in corpus]
vocab = sorted({w for doc in tokenized for w in doc})
N = len(corpus)

# Document frequency
df = {w: sum(1 for doc in tokenized if w in doc) for w in vocab}

# IDF (smoothed)
idf = {w: math.log((1 + N) / (1 + df[w])) + 1 for w in vocab}

# TF matrix (relative frequency)
tf_matrix = []
for doc in tokenized:
    counts = Counter(doc)
    total = len(doc)
    tf_matrix.append([counts[w] / total for w in vocab])
tf_df = pd.DataFrame(tf_matrix, columns=vocab, index=index)

# TF-IDF matrix (raw, before normalisation)
tfidf_manual = np.array(tf_matrix) * np.array([idf[w] for w in vocab])
manual_df = pd.DataFrame(tfidf_manual, columns=vocab, index=index)

print("\n" + "=" * 60)
print("TERM FREQUENCY (TF)")
print("=" * 60)
print(tf_df.round(3))

print("\n" + "=" * 60)
print("DOCUMENT FREQUENCY AND IDF")
print("=" * 60)
print(pd.DataFrame({"df": df, "idf": {w: round(v, 3) for w, v in idf.items()}}).T)

print("\n" + "=" * 60)
print("TF-IDF FROM SCRATCH")
print("=" * 60)
print(manual_df.round(3))

# ---------------------------------------------------------------
# 3. TF-IDF using scikit-learn
# ---------------------------------------------------------------
tfidf_vec = TfidfVectorizer()
X_tfidf = tfidf_vec.fit_transform(corpus)
sk_tfidf_df = pd.DataFrame(
    X_tfidf.toarray(), columns=tfidf_vec.get_feature_names_out(), index=index
)

print("\n" + "=" * 60)
print("TF-IDF USING sklearn TfidfVectorizer")
print("=" * 60)
print(sk_tfidf_df.round(3))

# Sanity check: sklearn uses raw counts for TF and L2 normalisation, so
# reproduce that on the manual side to verify the IDF logic is correct.
raw_counts = np.array([[Counter(doc)[w] for w in vocab] for doc in tokenized])
manual_sk_style = raw_counts * np.array([idf[w] for w in vocab])
norms = np.linalg.norm(manual_sk_style, axis=1, keepdims=True)
manual_sk_style = manual_sk_style / norms
print(
    "\nManual (count x IDF, L2-normalised) matches sklearn:",
    np.allclose(manual_sk_style, sk_tfidf_df.values),
)

# ---------------------------------------------------------------
# 4. BoW for comparison
# ---------------------------------------------------------------
bow_vec = CountVectorizer()
X_bow = bow_vec.fit_transform(corpus)
bow_df = pd.DataFrame(
    X_bow.toarray(), columns=bow_vec.get_feature_names_out(), index=index
)

print("\n" + "=" * 60)
print("BoW (RAW COUNTS)")
print("=" * 60)
print(bow_df)

# ---------------------------------------------------------------
# 5. Side-by-side comparison for one document
# ---------------------------------------------------------------
doc_name = "Doc 1"
comparison = pd.DataFrame(
    {
        "BoW count": bow_df.loc[doc_name],
        "TF-IDF weight": sk_tfidf_df.loc[doc_name].round(3),
        "IDF": pd.Series(dict(zip(tfidf_vec.get_feature_names_out(), tfidf_vec.idf_))).round(3),
    }
)
comparison = comparison[comparison["BoW count"] > 0].sort_values("TF-IDF weight", ascending=False)

print("\n" + "=" * 60)
print(f"BoW vs TF-IDF FOR {doc_name}: '{corpus[0]}'")
print("=" * 60)
print(comparison)

# ---------------------------------------------------------------
# 6. Top terms per document (TF-IDF vs BoW)
# ---------------------------------------------------------------
print("\n" + "=" * 60)
print("TOP-3 TERMS PER DOCUMENT")
print("=" * 60)
for name in index:
    top_bow = bow_df.loc[name].sort_values(ascending=False).head(3)
    top_tfidf = sk_tfidf_df.loc[name].sort_values(ascending=False).head(3)
    print(f"\n{name}")
    print("  BoW    :", ", ".join(f"{w}({v})" for w, v in top_bow.items()))
    print("  TF-IDF :", ", ".join(f"{w}({v:.3f})" for w, v in top_tfidf.items()))