# -*- coding: utf-8 -*-
"""Topic Modeling using Latent Semantic Analysis (LSA)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ow05IXjIqZ9fLhraC4zZbDK3BAa5O7U5
"""

# Topic Modeling using Latent Semantic Analysis (LSA)

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import TruncatedSVD

# Step 1: Create a sample dataset
documents = [
    "Machine learning and artificial intelligence are changing technology",
    "Deep learning uses neural networks for artificial intelligence",
    "Python programming is useful for machine learning and data science",
    "Cricket is a popular sport played with bat and ball",
    "Football is a famous sport played by many teams",
    "Cricket players practice batting bowling and fielding",
    "Hospitals use medical technology to improve patient healthcare",
    "Doctors use modern technology for medical diagnosis and treatment",
    "Healthcare and medical science help improve human health"
]

# Step 2: Convert text into TF-IDF features
vectorizer = TfidfVectorizer(
    stop_words="english"
)

tfidf_matrix = vectorizer.fit_transform(documents)

# Step 3: Apply Truncated SVD
# Reduce the document-term matrix to 3 topics
lsa_model = TruncatedSVD(
    n_components=3,
    random_state=42
)

lsa_matrix = lsa_model.fit_transform(tfidf_matrix)

# Step 4: Get feature names
terms = vectorizer.get_feature_names_out()

# Step 5: Display the topics
print("\nTopics discovered using LSA:\n")

for topic_index, topic in enumerate(lsa_model.components_):
    print(f"Topic {topic_index + 1}:")

    # Get indices of top 5 words
    top_indices = topic.argsort()[-5:][::-1]

    top_words = [terms[i] for i in top_indices]

    print(", ".join(top_words))
    print()

# Step 6: Display topic representation of documents
print("Document Topic Representation:\n")

for i, document_vector in enumerate(lsa_matrix):
    print(f"Document {i + 1}:")

    for topic_index, score in enumerate(document_vector):
        print(f"Topic {topic_index + 1}: {score:.3f}")

    print()

# Step 7: Display explained variance
print("Explained variance ratio:")

for i, variance in enumerate(
    lsa_model.explained_variance_ratio_
):
    print(f"Topic {i + 1}: {variance:.3f}")

print(
    "Total explained variance:",
    round(
        lsa_model.explained_variance_ratio_.sum(),
        3
    )
)