# -*- coding: utf-8 -*-
"""Topic Modeling using Latent Dirichlet Allocation (LDA)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nv8uRS8TyKBfhy_Ab50jhZCr7luCJ49D
"""

# Topic Modeling using Latent Dirichlet Allocation (LDA)

import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from gensim import corpora
from gensim.models import LdaModel

# Download required NLTK data
nltk.download("punkt")
nltk.download("stopwords")
nltk.download("punkt_tab")

# Step 1: Create a sample dataset
documents = [
    "Machine learning and artificial intelligence are changing technology",
    "Deep learning uses neural networks for artificial intelligence",
    "Python programming is useful for machine learning and data science",
    "Cricket is a popular sport played with bat and ball",
    "Football is a famous sport played by many teams",
    "Cricket players practice batting bowling and fielding",
    "Hospitals use medical technology to improve patient healthcare",
    "Doctors use modern technology for medical diagnosis and treatment",
    "Healthcare and medical science help improve human health"
]

# Step 2: Load stopwords
stop_words = set(stopwords.words("english"))

# Step 3: Preprocess the documents
processed_docs = []

for doc in documents:
    words = word_tokenize(doc.lower())

    words = [
        word for word in words
        if word.isalpha() and word not in stop_words
    ]

    processed_docs.append(words)

# Step 4: Create a dictionary
dictionary = corpora.Dictionary(processed_docs)

# Step 5: Convert documents into Bag-of-Words format
corpus = [
    dictionary.doc2bow(doc)
    for doc in processed_docs
]

# Step 6: Train the LDA model
lda_model = LdaModel(
    corpus=corpus,
    id2word=dictionary,
    num_topics=3,
    random_state=42,
    passes=20,
    iterations=100
)

# Step 7: Display the discovered topics
print("\nDiscovered Topics:\n")

topics = lda_model.print_topics(
    num_topics=3,
    num_words=5
)

for topic_id, topic_words in topics:
    print(f"Topic {topic_id + 1}: {topic_words}")

# Step 8: Display topic distribution for each document
print("\nTopic Distribution for Documents:\n")

for i, bow in enumerate(corpus):
    topic_distribution = lda_model.get_document_topics(
        bow,
        minimum_probability=0
    )

    print(f"Document {i + 1}:")
    for topic_id, probability in topic_distribution:
        print(
            f"  Topic {topic_id + 1}: "
            f"{probability:.3f}"
        )

# Step 9: Predict the topic of a new document
new_document = (
    "Artificial intelligence and machine learning "
    "are used in modern technology"
)

new_words = word_tokenize(new_document.lower())

new_words = [
    word for word in new_words
    if word.isalpha() and word not in stop_words
]

new_bow = dictionary.doc2bow(new_words)

new_topics = lda_model.get_document_topics(
    new_bow,
    minimum_probability=0
)

print("\nTopic Distribution for New Document:")

for topic_id, probability in new_topics:
    print(f"Topic {topic_id + 1}: {probability:.3f}")

dominant_topic = max(new_topics, key=lambda x: x[1])

print(
    "\nDominant Topic:",
    dominant_topic[0] + 1
)