# -*- coding: utf-8 -*-
"""Word2Vec Word Embeddings using Gensim on a Custom Corpus

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M85hCjNRQxjtyU0jZcG0Qv1tK2CyOyhp
"""

from gensim.models import Word2Vec

# 1. Create a custom corpus
corpus = [
    "I love machine learning",
    "Machine learning is a part of artificial intelligence",
    "Deep learning is a part of machine learning",
    "I love artificial intelligence",
    "Python is used for machine learning",
    "Python is a popular programming language",
    "Deep learning uses neural networks",
    "Neural networks are used in artificial intelligence",
    "I enjoy learning Python",
    "Machine learning and deep learning are useful"
]

# 2. Tokenize the sentences
sentences = [sentence.lower().split() for sentence in corpus]

print("Tokenized Corpus:")
for sentence in sentences:
    print(sentence)

# 3. Train the Word2Vec model
model = Word2Vec(
    sentences=sentences,
    vector_size=50,
    window=3,
    min_count=1,
    workers=1,
    sg=1,
    seed=42,
    epochs=100
)

# 4. Display the vector of a word
word = "learning"

print("\nWord:", word)
print("\nWord Embedding:")
print(model.wv[word])

# 5. Find similar words
print("\nWords similar to 'learning':")

similar_words = model.wv.most_similar("learning", topn=3)

for word, similarity in similar_words:
    print(word, ":", round(similarity, 4))

# 6. Check similarity between two words
similarity = model.wv.similarity("machine", "deep")

print("\nSimilarity between 'machine' and 'deep':")
print(round(similarity, 4))

# 7. Display vocabulary
print("\nVocabulary:")
print(model.wv.index_to_key)